<div class="uk-container uk-container-xsmall">
    <div class="panel-body">
        <form action="/login" class="form" method="post">
            <div class="uk-margin">
                <label for="InputEmail1">Email address</label>
                <input type="email" name="email" class="uk-input" id="InputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <div class="uk-margin">
                <label for="InputPassword1">Password</label>
                <input type="password" name="password" class="uk-input" id="InputPassword1" placeholder="Password">
            </div>
            <button class="uk-button uk-button-default">Submit</button>
        </form>
    </div>
</div>