
<?php if(!empty($reg_error)):?>
    <?php foreach($reg_error as $message) :?>
        <div class="uk-alert uk-alert-danger" >
            <a class="uk-close uk-alert-close"></a>
            <p> <?=$message;?> </p>
        </div>
    <?php endforeach;?>
<?php endif;?>

<div class="uk-container uk-container-xsmall">
    <div class="panel-body">
        <form action="/registration" class="uk-form" method="post">
            <div class="uk-margin">
                <label for="InputName">Login</label>
                <input type="text" name="username" class="uk-input" id="InputName" aria-describedby="nameHelp" placeholder="Login">
            </div>
            <div class="uk-margin">
                <label for="InputEmail1">Email address</label>
                <input type="email" name="email" class="uk-input" id="InputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <div class="uk-margin">
                <label for="InputPassword1">Password</label>
                <input type="password" name="password" class="uk-input" id="InputPassword1" placeholder="Password">
            </div>
            <button class="uk-button uk-button-default">Submit</button>
        </form>
    </div>
</div>